### ISSUE TITLE
Auto Close Fleets at DT

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#16] opened 2018-01-13 22:36 UTC
If the waitlist attempts to make ESI requests on a fleet that is no longer active in game CCP will return this error. `{'what': 'The specified proxy or server node (1392245) is dead'}}"}`.

To combat this issue the following safeguards should be completed:

- Auto close all registered fleets at 11:00 Eve time.
- Allow FCs to manually close fleets using the fleet management page.

**Comment by Makeshift** [comment] 2018-02-16 00:36
This is technically a duplicate of #19, because if the fleet fails to update 5 times, it deletes it, and if it's the final fleet (which it will be at downtime), it can then delete everybody on the waitlist. So I'm closing this one because of my crazy logic.

**Closed by Makeshift** 2018-02-16 00:36 UTC
Labels: Enhancement
