### ISSUE TITLE
[BUG] We should possibly avoid using the URL to pass through user feedback.

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#49] opened 2018-02-19 00:48 UTC
Maybe?
![image](https://user-images.githubusercontent.com/15701407/36359010-83da8ed4-157b-11e8-888f-1b93e5df61ab.png)

Just a thought.

**Comment by samuelgrant** [comment] 2018-02-19 00:49
https://incursions.makeshift.ninja/?info=Makeshift%20Storque%20is%20super%20gay

**Comment by dragonshardz** [comment] 2018-02-19 00:50
This can be misused for hilarious ends.

**Comment by Viscart** [comment] 2018-02-19 09:34
Intended feature.

**Comment by Makeshift** [comment] 2018-02-19 09:36
The absolute worst thing that somebody can do here is inject data into their own browser session, which can be achieved by editing the HTML anyway.

This was intended as temporary until all errors are transferred via sockets... which will still be client-side generated, so you'll still be able to do this.

no u

**Closed by Makeshift** 2018-02-19 09:36 UTC
Labels: Bug
